version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7
    working_directory: ~/circleci
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.06.0-ce
      - run:
          name: unit test
          command: |
            sudo pip install pytest mock setuptools pyyaml
            sudo pip install -U .
            sudo py.test circleci/test*.py
      - run:
          name: int test
          command: |
            sudo pip install pytest setuptools pyyaml
            sudo pip install -U .
            sudo py.test integration/test*.py
      - run:
          name: docker build
          command: |
            MUNGED_BRANCH=$(echo $CIRCLE_BRANCH | tr '/' '_')

            docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}

            docker build . \
              -t nanliu/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1} \
              -t nanliu/${CIRCLE_PROJECT_REPONAME}:${MUNGED_BRANCH} \
              --build-arg BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
              --build-arg GIT_SHA1=${CIRCLE_SHA1} \
              --build-arg GIT_TAG=${CIRCLE_TAG}

            if [[ -n "${CIRCLE_TAG}" ]]; then
              docker nanliu/${CIRCLE_PROJECT_REPONAME}:${MUNGED_BRANCH} nanliu/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_TAG}
              docker push nanliu/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}
              docker push nanliu/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_TAG}
            else
              docker push nanliu/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}
              docker push nanliu/${CIRCLE_PROJECT_REPONAME}:${MUNGED_BRANCH}
            fi

            curl -X POST https://hooks.microbadger.com/images/nanliu/circleci/g05525pyv2nt05fU5l8ZabGZyGE=
